In [31]:
## Load necessary packages
import os
import pandas as pd
import glob
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

## load the TCT related packages
from TCT import node_normalizer
from TCT import name_resolver
from TCT import translator_metakg
from TCT import translator_kpinfo
from TCT import translator_query
from TCT import TCT

## Define the version number
version_number = "08_10_2026"
deployment_date = "2026-08-10"

In [32]:
## Load the Biolink category and predicate dictionary for mapping subject, object, and predicate types
%run ./Biolink_category_and_predication_dictionary.ipynb

Date of last update:  2026-08-26
Order is to always process Node/category map first, since the Edeg/predicate map depends on biolink-complainat node values
-----------------------------------------------------------------------------------------------------------------------------
Dictionary: category_map, Key template: Subject_category or Object_category
------------------------------------------------------------------------------------------
Dictionary: predicate_map, Key template: (Subject_category, Object_category, Predicate)

In [33]:
## Load all helper functions
%run /Users/Weiqi0/ISB_working/Hadlock_lab/QI_ISB_Git_repo/TranslatorPharcogenomicsKG/Parser_helper_functions.ipynb

In [34]:
# print(category_map)

## Load files and convert them into separate node & edge files
* check all imported file structure

In [35]:
## Notice!! Please change the file path of following codes into your own
raw_files_path = '/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/Pharmacogenetic_Associations_table/'

## Define the output path for node & edge files after formatting
download_path_node_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/Pharmacogenetic_Associations_table_parsed_node_{version_number}.tsv'
download_path_edge_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/Pharmacogenetic_Associations_table_parsed_edge_{version_number}.tsv'

In [36]:
## Check all node files being read
## Read all BigGIM node csv file in group 1

for f in os.listdir(raw_files_path):
    if f.endswith('.csv'):
        print(f)

Pharmacogenetic_associations_table.csv

In [37]:
## Read each individual csv files
source_df = pd.read_csv(raw_files_path + 'Pharmacogenetic_associations_table.csv')

## Drop nan values
source_df = source_df.dropna(subset=['Drug', 'Gene'])

source_df.head(10)

,Drug,Gene,Affected_subgroups,Description_of_Gene_Drug_Interaction,Type
0,Abacavir,HLA-B,*57:01 allele positive,Results in higher adverse reaction risk (hyper...,Data Support Therapeutic Management Recommenda...
1,Abrocitinib,CYP2C19,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...
2,Amifampridine,NAT2,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...
3,Amifampridine Phosphate,NAT2,poor metabolizers,Results in higher systemic concentrations. Use...,Data Support Therapeutic Management Recommenda...
4,Amphetamine,CYP2D6,poor metabolizers,May affect systemic concentrations and adverse...,Data Support Therapeutic Management Recommenda...
5,Aripiprazole,CYP2D6,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...
6,Aripiprazole Lauroxil,CYP2D6,poor metabolizers,Results in higher systemic concentrations. Dos...,Data Support Therapeutic Management Recommenda...
7,Atomoxetine,CYP2D6,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...
8,Azathioprine,TPMT and/or NUDT15,intermediate or poor metabolizers,Alters systemic active metabolite concentratio...,Data Support Therapeutic Management Recommenda...
9,Belinostat,UGT1A1,*28/*28 (poor metabolizers),May result in higher systemic concentrations a...,Data Support Therapeutic Management Recommenda...

In [38]:
## check all unique values in the Description_of_Gene_Drug_Interaction column
unique_description_values = source_df['Description_of_Gene_Drug_Interaction'].unique()
# print(unique_description_values)

In [39]:
## check all unique values in the Description_of_Gene_Drug_Interaction column
unique_drug_values = source_df['Drug'].unique()
print(unique_drug_values)

['Abacavir' 'Abrocitinib' 'Amifampridine' 'Amifampridine Phosphate'
 'Amphetamine' 'Aripiprazole' 'Aripiprazole Lauroxil' 'Atomoxetine'
 'Azathioprine' 'Belinostat' 'Belzutifan' 'Brexpiprazole' 'Brivaracetam'
 'Capecitabine' 'Carbamazepine' 'Celecoxib' 'Citalopram' 'Clobazam'
 'Clopidogrel' 'Clozapine' 'Codeine' 'Deutetrabenazine' 'Dronabinol'
 'Eliglustat' 'Erdafitinib' 'Flibanserin' 'Flurbiprofen' 'Fluorouracil'
 'Fosphenytoin' 'Gefitinib' 'Iloperidone' 'Irinotecan' 'Lofexidine'
 'Meclizine' 'Meloxicam' 'Metoclopramide' 'Mercaptopurine' 'Mivacurium'
 'Nateglinide' 'Oliceridine' 'Pantoprazole' 'Phenytoin' 'Pimozide'
 'Piroxicam' 'Pitolisant' 'Propafenone' 'Sacituzumab Govitecan-hziy'
 'Siponimod' 'Succinylcholine' 'Tacrolimus' 'Tetrabenazine' 'Thioguanine'
 'Thioridazine' 'Tramadol' 'Valbenazine' 'Venlafaxine' 'Vortioxetine'
 'Warfarin' 'Allopurinol' 'Carvedilol' 'Cevimeline' 'Efavirenz'
 'Isoniazid' 'Lapatinib' 'Mavacamten' 'Nilotinib' 'Oxcarbazepine'
 'Pazopanib' 'Perphenazine' 'Procainamide' 'Simvastatin'
 'Sulfamethoxazole and Trimethoprim' 'Sulfasalazine' 'Tolterodine'
 'Voriconazole' 'Amitriptyline' 'Amoxapine' 'Atorvastatin' 'Avatrombopag'
 'Carisoprodol' 'Clomipramine' 'Darifenacin' 'Desipramine'
 'Dexlansoprazole' 'Diazepam' 'Dolutegravir' 'Donepezil' 'Doxepin'
 'Elagolix' 'Escitalopram' 'Esomeprazole' 'Fesoterodine' 'Fluvoxamine'
 'Galantamine' 'Hydralazine' 'Ibuprofen' 'Imipramine' 'Lansoprazole'
 'Metoprolol' 'Mirabegron' 'Nebivolol' 'Nortriptyline' 'Omeprazole'
 'Paroxetine' 'Propranolol' 'Protriptyline' 'Rabeprazole' 'Raltegravir'
 'Risperidone' 'Rosuvastatin' 'Tamoxifen' 'Tamsulosin' 'Trimipramine'
 'Viloxazine']

In [40]:
## check all unique values in the Description_of_Gene_Drug_Interaction column
unique_gene_values = source_df['Gene'].unique()
print(unique_gene_values)

['HLA-B' 'CYP2C19' 'NAT2' 'CYP2D6' 'TPMT and/or NUDT15' 'UGT1A1'
 'CYP2C19 and/or UGT2B17' 'DPYD' 'CYP2C9' 'BCHE' 'CYP3A5' 'CYP4F2'
 'VKORC1' 'HLA-A' 'CYP2B6' 'Nonspecific (NAT)' 'HLA-DRB1' 'HLA-DQA1'
 'SLCO1B1']

In [41]:
## Add new columns subject_category and object_category
source_df['subject_category'] = 'biolink:Gene'
source_df['object_category'] = 'biolink:Drug'
source_df['predicate'] = 'biolink:associated_with_response_to'

## change the name of columns from col(Drug) to col(subject_name) and col(Gene) to col(object_name) for pandas dataframe full_df
source_df = source_df.rename(columns={
    'Gene': 'subject_name',
    'Drug': 'object_name'
})

In [42]:
source_df.head(5)

,object_name,subject_name,Affected_subgroups,Description_of_Gene_Drug_Interaction,Type,subject_category,object_category,predicate
0,Abacavir,HLA-B,*57:01 allele positive,Results in higher adverse reaction risk (hyper...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to
1,Abrocitinib,CYP2C19,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to
2,Amifampridine,NAT2,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to
3,Amifampridine Phosphate,NAT2,poor metabolizers,Results in higher systemic concentrations. Use...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to
4,Amphetamine,CYP2D6,poor metabolizers,May affect systemic concentrations and adverse...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to

## Execute name resolver to try to find all corresponding identifiers in Translator
* use name_resolver.loopup() function
* use name_resolver.batch_lookup() function for batch mapping

In [43]:
## remove those rows causing issues and then use name_resolver
## drop rows with subject_name in
list_subjects_to_keep = ['HLA-B', 'CYP2C19', 'NAT2', 'CYP2D6', 'UGT1A1', 'DPYD', 'CYP2C9', 'BCHE', 'CYP3A5', 'CYP4F2', 'VKORC1', 'HLA-A', 'CYP2B6', 'HLA-DRB1', 'HLA-DQA1', 'SLCO1B1']
source_filter_df = source_df[source_df['subject_name'].isin(list_subjects_to_keep)]

list_objects_to_keep = ['Abacavir', 'Abrocitinib', 'Amifampridine', 'Amifampridine Phosphate',
 'Amphetamine', 'Aripiprazole', 'Aripiprazole Lauroxil', 'Atomoxetine',
 'Azathioprine', 'Belinostat', 'Belzutifan', 'Brexpiprazole', 'Brivaracetam',
 'Capecitabine', 'Carbamazepine', 'Celecoxib', 'Citalopram', 'Clobazam',
 'Clopidogrel', 'Clozapine', 'Codeine', 'Deutetrabenazine', 'Dronabinol',
 'Eliglustat', 'Erdafitinib', 'Flibanserin', 'Flurbiprofen', 'Fluorouracil',
 'Fosphenytoin', 'Gefitinib', 'Iloperidone', 'Irinotecan', 'Lofexidine',
 'Meclizine', 'Meloxicam', 'Metoclopramide', 'Mercaptopurine', 'Mivacurium',
 'Nateglinide', 'Oliceridine', 'Pantoprazole', 'Phenytoin', 'Pimozide',
 'Piroxicam', 'Pitolisant', 'Propafenone', 'Sacituzumab Govitecan-hziy',
 'Siponimod', 'Succinylcholine', 'Tacrolimus', 'Tetrabenazine', 'Thioguanine',
 'Thioridazine', 'Tramadol', 'Valbenazine', 'Venlafaxine', 'Vortioxetine',
 'Warfarin', 'Allopurinol', 'Carvedilol', 'Cevimeline', 'Efavirenz',
 'Isoniazid', 'Lapatinib', 'Mavacamten', 'Nilotinib', 'Oxcarbazepine',
 'Pazopanib', 'Perphenazine', 'Procainamide', 'Simvastatin',
 'Sulfasalazine', 'Tolterodine', 'Voriconazole', 'Amitriptyline', 'Amoxapine', 'Atorvastatin', 'Avatrombopag',
 'Carisoprodol', 'Clomipramine', 'Darifenacin', 'Desipramine',
 'Dexlansoprazole', 'Diazepam', 'Dolutegravir', 'Donepezil', 'Doxepin',
 'Elagolix', 'Escitalopram', 'Esomeprazole', 'Fesoterodine', 'Fluvoxamine',
 'Galantamine', 'Hydralazine', 'Ibuprofen', 'Imipramine', 'Lansoprazole',
 'Metoprolol', 'Mirabegron', 'Nebivolol', 'Nortriptyline', 'Omeprazole',
 'Paroxetine', 'Propranolol', 'Protriptyline', 'Rabeprazole', 'Raltegravir',
 'Risperidone', 'Rosuvastatin', 'Tamoxifen', 'Tamsulosin', 'Trimipramine',
 'Viloxazine']

source_filter_df2 = source_filter_df[source_filter_df['object_name'].isin(list_objects_to_keep)]

In [44]:
# ## test case - Name resolver red flag...
# name = 'Nonspecific (NAT)'
# input_node_info = name_resolver.lookup(name)
# print(input_node_info)

In [45]:
# ## test case - Name resolver red flag...
# name = 'Nonspecific (NAT)'
# input_node_info = name_resolver.lookup(name, return_top_response = False)
# print(input_node_info)

In [46]:
# ## test case - another red flag?
# name = 'CYP2C19 and/or UGT2B17'
# input_node_info = name_resolver.lookup(name)
# print(input_node_info)

In [47]:
# ## test case - another red flag?
# name = 'CYP2C19 and/or UGT2B17'
# input_node_info = name_resolver.lookup(name, return_top_response = False)
# print(input_node_info)

In [48]:
# ## test case - correct
# name = 'BCHE'
# input_node_info = name_resolver.lookup(name)
# print(input_node_info)

In [49]:
# print(input_node_info.curie)

In [50]:
## Apply name_resolver.lookup and extract .curie for subject name
# source_df['subject'] = source_df['subject_name'].apply(lambda name: name_resolver.lookup(name).curie if name_resolver.lookup(name) else None)

## if True, then the function will only give the first matched row/record
## return_top_response = False

## switch to use batch_lookup?
import pandas as pd

# Get all names
names = source_filter_df2['subject_name'].tolist()

# Break into batches of 25
batch_size = 25
batches = [names[i:i + batch_size] for i in range(0, len(names), batch_size)]

# Run batch lookups and collect results
results = {}
for batch in batches:
    print("Current name handling is: ", batch)
    lookup_results = name_resolver.batch_lookup(batch)  # Expected to return a dict: {name: result or None}
    for name, result in lookup_results.items():
        results[name] = result.curie if result else None

# Map the resolved CURIEs back to the DataFrame
source_filter_df2['subject'] = source_filter_df2['subject_name'].map(results)

Current name handling is:  ['HLA-B', 'CYP2C19', 'NAT2', 'NAT2', 'CYP2D6', 'CYP2D6', 'CYP2D6', 'CYP2D6', 'UGT1A1', 'CYP2D6', 'CYP2C19', 'DPYD', 'HLA-B', 'CYP2C9', 'CYP2C19', 'CYP2C19', 'CYP2C19', 'CYP2D6', 'CYP2D6', 'CYP2D6', 'CYP2C9', 'CYP2D6', 'CYP2C9', 'CYP2C19', 'CYP2C9']
Current name handling is:  ['DPYD', 'CYP2C9', 'HLA-B', 'CYP2D6', 'CYP2D6', 'UGT1A1', 'CYP2D6', 'CYP2D6', 'CYP2C9', 'CYP2D6', 'BCHE', 'CYP2C9', 'CYP2D6', 'CYP2C19', 'CYP2C9', 'HLA-B', 'CYP2D6', 'CYP2C9', 'CYP2D6', 'CYP2D6', 'UGT1A1', 'CYP2C9', 'BCHE', 'CYP3A5', 'CYP2D6']
Current name handling is:  ['CYP2D6', 'CYP2D6', 'CYP2D6', 'CYP2D6', 'CYP2D6', 'CYP2C9', 'CYP4F2', 'VKORC1', 'HLA-B', 'HLA-A', 'CYP2D6', 'CYP2D6', 'CYP2D6', 'CYP2B6', 'HLA-DRB1', 'HLA-DQA1', 'CYP2C19', 'UGT1A1', 'HLA-B', 'HLA-B', 'UGT1A1', 'CYP2D6', 'SLCO1B1', 'CYP2D6', 'CYP2D6']
Current name handling is:  ['CYP2C19', 'CYP2D6', 'CYP2D6', 'SLCO1B1', 'CYP2C9', 'CYP2C19', 'CYP2D6', 'CYP2D6', 'CYP2D6', 'CYP2C19', 'CYP2C19', 'UGT1A1', 'CYP2D6', 'CYP2C19', 'CYP2D6', 'SLCO1B1', 'CYP2C19', 'CYP2C19', 'CYP2D6', 'CYP2D6', 'CYP2D6', 'CYP2C9', 'CYP2D6', 'CYP2C19', 'CYP2D6']
Current name handling is:  ['CYP2D6', 'CYP2D6', 'CYP2D6', 'CYP2C19', 'CYP2D6', 'CYP2D6', 'CYP2D6', 'CYP2C19', 'UGT1A1', 'CYP2D6', 'SLCO1B1', 'CYP2D6', 'CYP2D6', 'CYP2D6', 'CYP2D6']

In [51]:
source_filter_df2.head(5)

,object_name,subject_name,Affected_subgroups,Description_of_Gene_Drug_Interaction,Type,subject_category,object_category,predicate,subject
0,Abacavir,HLA-B,*57:01 allele positive,Results in higher adverse reaction risk (hyper...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:3106
1,Abrocitinib,CYP2C19,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:1557
2,Amifampridine,NAT2,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:116632
3,Amifampridine Phosphate,NAT2,poor metabolizers,Results in higher systemic concentrations. Use...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:116632
4,Amphetamine,CYP2D6,poor metabolizers,May affect systemic concentrations and adverse...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:1565

In [52]:
## switch to use batch_lookup?
import pandas as pd

# Get all names
names = source_filter_df2['object_name'].tolist()

# Break into batches of 25
batch_size = 25
batches = [names[i:i + batch_size] for i in range(0, len(names), batch_size)]

# Run batch lookups and collect results
results = {}
for batch in batches:
    print("Current name handling is: ", batch)
    lookup_results = name_resolver.batch_lookup(batch)  # Expected to return a dict: {name: result or None}
    for name, result in lookup_results.items():
        results[name] = result.curie if result else None

# Map the resolved CURIEs back to the DataFrame
source_filter_df2['object'] = source_filter_df2['object_name'].map(results)

Current name handling is:  ['Abacavir', 'Abrocitinib', 'Amifampridine', 'Amifampridine Phosphate', 'Amphetamine', 'Aripiprazole', 'Aripiprazole Lauroxil', 'Atomoxetine', 'Belinostat', 'Brexpiprazole', 'Brivaracetam', 'Capecitabine', 'Carbamazepine', 'Celecoxib', 'Citalopram', 'Clobazam', 'Clopidogrel', 'Clozapine', 'Codeine', 'Deutetrabenazine', 'Dronabinol', 'Eliglustat', 'Erdafitinib', 'Flibanserin', 'Flurbiprofen']
Current name handling is:  ['Fluorouracil', 'Fosphenytoin', 'Fosphenytoin', 'Gefitinib', 'Iloperidone', 'Irinotecan', 'Lofexidine', 'Meclizine', 'Meloxicam', 'Metoclopramide', 'Mivacurium', 'Nateglinide', 'Oliceridine', 'Pantoprazole', 'Phenytoin', 'Phenytoin', 'Pimozide', 'Piroxicam', 'Pitolisant', 'Propafenone', 'Sacituzumab Govitecan-hziy', 'Siponimod', 'Succinylcholine', 'Tacrolimus', 'Tetrabenazine']
Current name handling is:  ['Thioridazine', 'Tramadol', 'Valbenazine', 'Venlafaxine', 'Vortioxetine', 'Warfarin', 'Warfarin', 'Warfarin', 'Allopurinol', 'Carbamazepine', 'Carvedilol', 'Cevimeline', 'Codeine', 'Efavirenz', 'Lapatinib', 'Lapatinib', 'Mavacamten', 'Nilotinib', 'Oxcarbazepine', 'Pazopanib', 'Pazopanib', 'Perphenazine', 'Simvastatin', 'Tolterodine', 'Tramadol']
Current name handling is:  ['Voriconazole', 'Amitriptyline', 'Amoxapine', 'Atorvastatin', 'Avatrombopag', 'Carisoprodol', 'Clomipramine', 'Darifenacin', 'Desipramine', 'Dexlansoprazole', 'Diazepam', 'Dolutegravir', 'Donepezil', 'Doxepin', 'Doxepin', 'Elagolix', 'Escitalopram', 'Esomeprazole', 'Fesoterodine', 'Fluvoxamine', 'Galantamine', 'Ibuprofen', 'Imipramine', 'Lansoprazole', 'Metoprolol']
Current name handling is:  ['Mirabegron', 'Nebivolol', 'Nortriptyline', 'Omeprazole', 'Paroxetine', 'Propranolol', 'Protriptyline', 'Rabeprazole', 'Raltegravir', 'Risperidone', 'Rosuvastatin', 'Tamoxifen', 'Tamsulosin', 'Trimipramine', 'Viloxazine']

In [53]:
source_filter_df2.head(5)

,object_name,subject_name,Affected_subgroups,Description_of_Gene_Drug_Interaction,Type,subject_category,object_category,predicate,subject,object
0,Abacavir,HLA-B,*57:01 allele positive,Results in higher adverse reaction risk (hyper...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:3106,CHEBI:421707
1,Abrocitinib,CYP2C19,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:1557,UNII:73SM5SF3OR
2,Amifampridine,NAT2,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:116632,CHEBI:135948
3,Amifampridine Phosphate,NAT2,poor metabolizers,Results in higher systemic concentrations. Use...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:116632,CHEBI:135948
4,Amphetamine,CYP2D6,poor metabolizers,May affect systemic concentrations and adverse...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:1565,CHEBI:132233

In [54]:
edge_clean_df = source_filter_df2.copy()

## Drop those unmatched rows
## Drop rows where 'name' is NaN, None, or empty string
edge_clean_df = edge_clean_df[~edge_clean_df['predicate'].isna() & (edge_clean_df['predicate'].str.strip() != '')]

## add knowledge source column
edge_clean_df['knowledge_source'] = 'FDA Table of Pharmacogenetic Associations'

edge_clean_df['provided_by'] = 'FDA Table of Pharmacogenetic Associations'

## add a new knowledge_level column and set value to be 'knowledge_assertion'
edge_clean_df['knowledge_level'] = 'knowledge_assertion'

## add a new agent_type column and set value to be 'manual_agent'
edge_clean_df['agent_type'] = 'manual_agent'

## Cast to standard 'object' dtype and add prefix
edge_clean_df['publications'] = None

## add a deployment date label
edge_clean_df['deploy_date'] = deployment_date

## create a context_qualifier column information from the col('therapies') and fill na if this column is empty
## if all of them are empty, then fill na
edge_clean_df['context_qualifier'] = edge_clean_df['Affected_subgroups']

### Add resources_id column, checking whether edge is already
column_list = ['subject', 'predicate', 'object', 'context_qualifier', 'deploy_date']
# Apply the function to each row to generate UUIDs
edge_clean_df['id'] = edge_clean_df[column_list].apply(generate_uuid, axis=1)

In [55]:
edge_parsing_df = edge_clean_df.copy()

### Put additional columns into attribute column
import pandas as pd
import json

ATTRIBUTE_CONFIG = {
    "Description_of_Gene_Drug_Interaction": {
        "attribute_type_id": "biolink:has_qualitative_value",
        "value_type_id": "FDA_association_table:Description_of_Gene_Drug_Interaction",
        "attribute_source": "infores:FDA_association_table",
    },
    "Type": {
        "attribute_type_id": "biolink:has_qualitative_value",
        "value_type_id": "FDA_association_table:Type",
        "attribute_source": "infores:FDA_association_table",
    },
}

def group_into_attributes(row, config):
    return [
        {
            "attribute_type_id": meta["attribute_type_id"],
            "value": str(row[col]).strip(),
            "value_type_id": meta["value_type_id"],
            "original_attribute_name": col,
            "attribute_source": meta["attribute_source"],
        }
        for col, meta in config.items()
        if pd.notna(row[col]) and str(row[col]).strip() != ""
    ]

edge_parsing_df["attributes"] = edge_parsing_df.apply(lambda r: group_into_attributes(r, ATTRIBUTE_CONFIG), axis=1)

In [56]:
edge_parsing_df.head(5)

,object_name,subject_name,Affected_subgroups,Description_of_Gene_Drug_Interaction,Type,subject_category,object_category,predicate,subject,object,knowledge_source,provided_by,knowledge_level,agent_type,publications,deploy_date,context_qualifier,id,attributes
0,Abacavir,HLA-B,*57:01 allele positive,Results in higher adverse reaction risk (hyper...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:3106,CHEBI:421707,FDA Table of Pharmacogenetic Associations,FDA Table of Pharmacogenetic Associations,knowledge_assertion,manual_agent,None,2026-08-10,*57:01 allele positive,f6519b12-7179-5a65-889a-e890ee0195cc,[{'attribute_type_id': 'biolink:has_qualitativ...
1,Abrocitinib,CYP2C19,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:1557,UNII:73SM5SF3OR,FDA Table of Pharmacogenetic Associations,FDA Table of Pharmacogenetic Associations,knowledge_assertion,manual_agent,None,2026-08-10,poor metabolizers,656f2adf-e135-5ae2-812e-9ef12b2182d2,[{'attribute_type_id': 'biolink:has_qualitativ...
2,Amifampridine,NAT2,poor metabolizers,Results in higher systemic concentrations and ...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:116632,CHEBI:135948,FDA Table of Pharmacogenetic Associations,FDA Table of Pharmacogenetic Associations,knowledge_assertion,manual_agent,None,2026-08-10,poor metabolizers,b6b3dfed-d6c4-5131-9b68-0b1c992b2a99,[{'attribute_type_id': 'biolink:has_qualitativ...
3,Amifampridine Phosphate,NAT2,poor metabolizers,Results in higher systemic concentrations. Use...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:116632,CHEBI:135948,FDA Table of Pharmacogenetic Associations,FDA Table of Pharmacogenetic Associations,knowledge_assertion,manual_agent,None,2026-08-10,poor metabolizers,b6b3dfed-d6c4-5131-9b68-0b1c992b2a99,[{'attribute_type_id': 'biolink:has_qualitativ...
4,Amphetamine,CYP2D6,poor metabolizers,May affect systemic concentrations and adverse...,Data Support Therapeutic Management Recommenda...,biolink:Gene,biolink:Drug,biolink:associated_with_response_to,NCBIGene:1565,CHEBI:132233,FDA Table of Pharmacogenetic Associations,FDA Table of Pharmacogenetic Associations,knowledge_assertion,manual_agent,None,2026-08-10,poor metabolizers,286e5975-daaf-57b8-85a5-d43127fa4666,[{'attribute_type_id': 'biolink:has_qualitativ...

In [57]:
## add qualifiers
edge_parsing_df['subject_direction_qualifier'] = None
edge_parsing_df['object_direction_qualifier'] = None
edge_parsing_df['object_aspect_qualifier'] = None

In [58]:
## reorder the dataframe
desired_order = [
    'subject', 'subject_name', 'subject_category', 'object', 'object_name', 'object_category', 
    'predicate', 'subject_direction_qualifier', 'object_direction_qualifier', 'object_aspect_qualifier',
    'provided_by', 'knowledge_source', 'publications', 'knowledge_level', 'context_qualifier', 'agent_type', 
    'deploy_date', 'id', 'attributes'
]

edge_parsing_df = edge_parsing_df[desired_order]

print(edge_parsing_df.columns.tolist())

['subject', 'subject_name', 'subject_category', 'object', 'object_name', 'object_category', 'predicate', 'subject_direction_qualifier', 'object_direction_qualifier', 'object_aspect_qualifier', 'provided_by', 'knowledge_source', 'publications', 'knowledge_level', 'context_qualifier', 'agent_type', 'deploy_date', 'id', 'attributes']

### now create the corresponding node dataframe directly from the finalized edge dataframe
* only need three columns: id, name, category

In [59]:
node_subject_df = edge_parsing_df[['subject', 'subject_name', 'subject_category']]
node_object_df = edge_parsing_df[['object', 'object_name', 'object_category']]

## rename those columns into desired format
node_subject_df.rename(columns={'subject': 'id', 'subject_name': 'name', 'subject_category': 'category'}, inplace=True)
node_object_df.rename(columns={'object': 'id', 'object_name': 'name', 'object_category': 'category'}, inplace=True)

concat_node_df = pd.concat([node_subject_df, node_object_df]).drop_duplicates(keep='first')

concat_node_df.head(2)

/var/folders/ml/cjwyk2ps62361rr96_3b_n080000gp/T/ipykernel_54530/1675134899.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  node_subject_df.rename(columns={'subject': 'id', 'subject_name': 'name', 'subject_category': 'category'}, inplace=True)
/var/folders/ml/cjwyk2ps62361rr96_3b_n080000gp/T/ipykernel_54530/1675134899.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  node_object_df.rename(columns={'object': 'id', 'object_name': 'name', 'object_category': 'category'}, inplace=True)

              id     name      category
0  NCBIGene:3106    HLA-B  biolink:Gene
1  NCBIGene:1557  CYP2C19  biolink:Gene

## following codes are used for quality control and sanity check
* check and confirm all subject & object types are correctly formatted

In [60]:
## check all unique predicate values
counts = concat_node_df['category'].value_counts()
print(counts)

category
biolink:Drug    105
biolink:Gene     16
Name: count, dtype: int64

In [61]:
## check all unique predicate values
counts = edge_parsing_df['predicate'].value_counts()
print(counts)

predicate
biolink:associated_with_response_to    115
Name: count, dtype: int64

In [62]:
## Create a graph from the DataFrame
graph = nx.from_pandas_edgelist(edge_parsing_df, 'subject', 'object', edge_attr='predicate')

## Print graph information
print('Number of nodes', len(set(graph.nodes)))
print('Number of edges', len(set(graph.edges)))
print('Average degree', sum(dict(graph.degree).values()) / len(graph.nodes))

Number of nodes 120
Number of edges 112
Average degree 1.8666666666666667

## Now output those parsed files
*

In [63]:
## Define the output path for node & edge files after formatting
download_path_node_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/Pharmacogenetic_Associations_table_parsed_node_{version_number}.tsv'
download_path_edge_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/Pharmacogenetic_Associations_table_parsed_edge_{version_number}.tsv'

## download both node and edge files
## Download the result df
## disable download for testing
concat_node_df.to_csv(download_path_node_file, sep ='\t', index=False)
edge_parsing_df.to_csv(download_path_edge_file, sep ='\t', index=False)

In [64]:
print(download_path_node_file)

/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/Pharmacogenetic_Associations_table_parsed_node_08_10_2026.tsv