In [27]:
## Load necessary packages
import os
import pandas as pd
import glob
import numpy as np
import networkx as nx
# import matplotlib.pyplot as plt

## load the needed tqdm package
from tqdm import tqdm

# Enable tqdm for pandas apply
tqdm.pandas()

## Define the version number
## past versions:
# version_number = "08_18_2025"
# deployment_date = "2025-08-18"

## current version number
version_number = "08_30_2026"

In [2]:
## Load files and concatenate them into one merge tsv file

In [28]:
## Notice!! Please change the file path of following codes into your own
raw_files_path = '/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/'

## Check all node files being read
## Read all BigGIM node csv file in group 1

for f in os.listdir(raw_files_path):
    if f.endswith('.tsv'):
        print(f)

GtoPdB_approved_drug_detailed_interactions_parsed_node_01_06_2026.tsv
GtoPdB_approved_drug_detailed_interactions_parsed_edge_01_06_2026.tsv
FDA_Pharmacogenomic_biomarkers_parsed_edge_09_04_2025.tsv
FDA_Pharmacogenomic_biomarkers_parsed_node_09_04_2025.tsv
Pharmacogenomics_KG_parsed_node_08_18_2025.tsv
SINGNOR_parsed_node_08_18_2025.tsv
SINGNOR_parsed_edge_08_18_2025.tsv
Pharmacogenomics_KG_parsed_edge_08_18_2025.tsv
PrimeKG_parsed_edge_01_06_2026.tsv
PrimeKG_parsed_node_01_06_2026.tsv
CIViC_parsed_edge_08_10_2026.tsv
CIViC_parsed_node_08_10_2026.tsv
Pharmacogenetic_Associations_table_parsed_node_08_10_2025.tsv
Pharmacogenetic_Associations_table_parsed_edge_08_10_2025.tsv
PrimeKG_parsed_edge_08_10_2026.tsv
Pharmacogenetic_Associations_table_parsed_node_08_10_2026.tsv
PrimeKG_parsed_node_08_10_2026.tsv
Pharmacogenetic_Associations_table_parsed_edge_08_10_2026.tsv
PharmGKB_parsed_edge_09_04_2025.tsv
PharmGKB_parsed_node_09_04_2025.tsv
Pharmacogenomics_KG_parsed_node_01_06_2026.tsv
SINGNOR_parsed_edge_09_04_2025.tsv
Pharmacogenomics_KG_parsed_edge_09_04_2025.tsv
Pharmacogenomics_KG_parsed_node_09_04_2025.tsv
SINGNOR_parsed_node_09_04_2025.tsv
Pharmacogenomics_KG_parsed_edge_01_06_2026.tsv
CPIC_parsed_node_08_10_2026.tsv
CPIC_parsed_edge_08_10_2026.tsv

- Phase 1 deployment contains:
- Date: 2025-09-04
    - FDA Pharmacogenomic Biomarker
    - PharmGKB
    - SIGNOR
- Phase 2 deployment contains:
- Date: 2026-01-06
    - GtoPdB
- Phase 3 deployment contains:
- Date: 2026-08-10
    - PrimeKG (updated)
    - FDA pharmacogenetic associations table
    - CPIC
    - CIVIC

### Read the current version of FDA Pharmacogenomic Biomarker parsed files

In [29]:
## define phase one version number
version_number = "09_04_2025"

In [30]:
## Define the output path for node & edge files after formatting
FDA_Pharmacogenomic_biomarkers_path_node_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/FDA_Pharmacogenomic_biomarkers_parsed_node_{version_number}.tsv'
FDA_Pharmacogenomic_biomarkers_path_edge_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/FDA_Pharmacogenomic_biomarkers_parsed_edge_{version_number}.tsv'


## Read each individual csv files
FDA_Pharmacogenomic_biomarkers_node_df = pd.read_csv(FDA_Pharmacogenomic_biomarkers_path_node_file, sep='\t')
FDA_Pharmacogenomic_biomarkers_edge_df = pd.read_csv(FDA_Pharmacogenomic_biomarkers_path_edge_file, sep='\t')

In [31]:
FDA_Pharmacogenomic_biomarkers_node_df.head(2)

              id          name      category
0  RXCUI:2563966   Odevixibat   biolink:Drug
1  RXCUI:2571074  Maralixibat   biolink:Drug

In [32]:
FDA_Pharmacogenomic_biomarkers_edge_df.head(2)

,subject,subject_name,subject_category,object,object_name,object_category,predicate,knowledge_source,knowledge_level,context_qualifier,agent_type,deploy_date,id
0,RXCUI:2563966,Odevixibat,biolink:Drug,NCBIGene:8647,ABCB11,biolink:Gene,biolink:has_biomarker,FDA pharmacogenomics biomarkers table,knowledge_assertion,Gastroenterology,text_mining_agent,2025-09-04,4e1f7def-7e8d-5204-9826-56887ff5ecb5
1,RXCUI:2571074,Maralixibat,biolink:Drug,NCBIGene:8647,ABCB11,biolink:Gene,biolink:has_biomarker,FDA pharmacogenomics biomarkers table,knowledge_assertion,Gastroenterology,text_mining_agent,2025-09-04,d5f51f86-e8a1-5481-8105-cdd2d9efc023

### Read the current version of PharmGKB parsed files

In [33]:
## Define the output path for node & edge files after formatting
PharmGKB_path_node_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/PharmGKB_parsed_node_{version_number}.tsv'
PharmGKB_path_edge_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/PharmGKB_parsed_edge_{version_number}.tsv'


## Read each individual csv files
PharmGKB_node_df = pd.read_csv(PharmGKB_path_node_file, sep='\t')
PharmGKB_edge_df = pd.read_csv(PharmGKB_path_edge_file, sep='\t')

In [34]:
PharmGKB_node_df.head(2)

                id    name      category
0  NCBIGene:162282  ANKFN1  biolink:Gene
1    NCBIGene:1728    NQO1  biolink:Gene

In [35]:
PharmGKB_edge_df.head(2)

,subject,subject_name,subject_category,object,object_name,object_category,predicate,subject_direction_qualifier,object_direction_qualifier,object_aspect_qualifier,knowledge_source,publications,knowledge_level,context_qualifier,agent_type,deploy_date,id
0,NCBIGene:162282,ANKFN1,biolink:Gene,MeSH:D000075222,Essential hypertension,biolink:Disease,biolink:associated_with,NaN,NaN,NaN,PharmGKB,25695618,knowledge_assertion,NaN,automated_agent,2025-09-04,6f18147d-d001-5ded-8c31-fcadee67b9b6
1,NCBIGene:162282,ANKFN1,biolink:Gene,PUBCHEM.COMPOUND:3639,hydrochlorothiazide,biolink:ChemicalEntity,biolink:associated_with,NaN,NaN,NaN,PharmGKB,25695618,knowledge_assertion,NaN,automated_agent,2025-09-04,5cd4233b-a59b-5a12-aecc-f64b1e382abe

### Read the current version of SIGNOR parsed files

In [36]:
## Define the output path for node & edge files after formatting
SIGNOR_path_node_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/SINGNOR_parsed_node_{version_number}.tsv'
SIGNOR_path_edge_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/SINGNOR_parsed_edge_{version_number}.tsv'


## Read each individual csv files
signor_node_df = pd.read_csv(SIGNOR_path_node_file, sep='\t')
signor_edge_df = pd.read_csv(SIGNOR_path_edge_file, sep='\t')

In [37]:
signor_node_df.head(2)

              id     name      category
0  NCBIGene:1457  CSNK2A1  biolink:Gene
1  NCBIGene:2932    GSK3B  biolink:Gene

In [38]:
signor_edge_df.head(2)

,subject,subject_name,subject_category,object,object_name,object_category,predicate,subject_direction_qualifier,object_direction_qualifier,object_aspect_qualifier,provided_by,knowledge_source,publications,knowledge_level,context_qualifier,agent_type,deploy_date,id
0,NCBIGene:1457,CSNK2A1,biolink:Gene,NCBIGene:11036,GTF2A1L,biolink:Gene,biolink:regulates,NaN,upregulated,activity or abundance,SIGNOR,SIGNOR-250870,PMID:36243968|PMID:12107178,knowledge_assertion,NaN,automated_agent,2025-09-04,b16fe51d-26ac-592a-811d-6efd09fb6e5e
1,NCBIGene:2932,GSK3B,biolink:Gene,NCBIGene:6688,SPI1,biolink:Gene,biolink:regulates,NaN,downregulated,activity or abundance,SIGNOR,SIGNOR-277542,PMID:36243968|PMID:33188146,knowledge_assertion,NaN,automated_agent,2025-09-04,a5901d89-1d80-55bd-b561-3ab5fe52b37f

### Read the current version of PrimeKG parsed files

In [39]:
version_number = "08_10_2026"

## Define the output path for node & edge files after formatting
PrimeKG_path_node_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/PrimeKG_parsed_node_{version_number}.tsv'
PrimeKG_path_edge_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/PrimeKG_parsed_edge_{version_number}.tsv'

## download both node and edge files
## Download the result df
PrimeKG_node_df = pd.read_csv(PrimeKG_path_node_file, sep ='\t')
PrimeKG_edge_df = pd.read_csv(PrimeKG_path_edge_file, sep ='\t')

In [40]:
PrimeKG_node_df.head(2)

              id    name      category
0  NCBIGene:9796  PHYHIP  biolink:Gene
1  NCBIGene:7918  GPANK1  biolink:Gene

In [41]:
PrimeKG_edge_df.head(2)

,subject,subject_name,subject_category,object,object_name,object_category,predicate,subject_direction_qualifier,object_direction_qualifier,object_aspect_qualifier,provided_by,knowledge_source,publications,knowledge_level,context_qualifier,agent_type,deploy_date,id
0,NCBIGene:9796,PHYHIP,biolink:Gene,NCBIGene:56992,KIF15,biolink:Gene,biolink:physical_interacts_with,NaN,NaN,NaN,PrimeKG,PrimeKG,NaN,knowledge_assertion,NaN,automated_agent,2026-08-10,c95895d9-23c0-5d69-a5f4-0d4cd66e3d82
1,NCBIGene:7918,GPANK1,biolink:Gene,NCBIGene:9240,PNMA1,biolink:Gene,biolink:physical_interacts_with,NaN,NaN,NaN,PrimeKG,PrimeKG,NaN,knowledge_assertion,NaN,automated_agent,2026-08-10,6f2fe3f0-b057-50ca-b038-16a322223d02

## Merge phase 2 new sources

In [16]:
### Read the current version of GtoPdB parsed files

In [42]:
version_number = "01_06_2026"

## Define the output path for node & edge files after formatting
GtoPdB_path_node_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/GtoPdB_approved_drug_detailed_interactions_parsed_node_{version_number}.tsv'
GtoPdB_path_edge_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/GtoPdB_approved_drug_detailed_interactions_parsed_edge_{version_number}.tsv'

## download both node and edge files
## Download the result df
GtoPdB_node_df = pd.read_csv(GtoPdB_path_node_file, sep ='\t')
GtoPdB_edge_df = pd.read_csv(GtoPdB_path_edge_file, sep ='\t')

## Merge phase 3 new sources

In [45]:
## define the version number
version_number = "08_10_2026"

In [46]:
## Define the output path for node & edge files after formatting
CIViC_path_node_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/CIViC_parsed_node_{version_number}.tsv'
CIViC_path_edge_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/CIViC_parsed_edge_{version_number}.tsv'

## download both node and edge files
## Download the result df
CIViC_node_df = pd.read_csv(CIViC_path_node_file, sep ='\t')
CIViC_edge_df = pd.read_csv(CIViC_path_edge_file, sep ='\t')

In [47]:
## Define the output path for node & edge files after formatting
CPIC_path_node_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/CPIC_parsed_node_{version_number}.tsv'
CPIC_path_edge_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/CPIC_parsed_edge_{version_number}.tsv'

## download both node and edge files
## Download the result df
CPIC_node_df = pd.read_csv(CPIC_path_node_file, sep ='\t')
CPIC_edge_df = pd.read_csv(CPIC_path_edge_file, sep ='\t')

In [48]:
## Define the output path for node & edge files after formatting
Pharmacogenetic_Associations_table_path_node_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/Pharmacogenetic_Associations_table_parsed_node_{version_number}.tsv'
Pharmacogenetic_Associations_table_path_edge_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/Pharmacogenetic_Associations_table_parsed_edge_{version_number}.tsv'

## download both node and edge files
## Download the result df
Pharmacogenetic_Associations_table_node_df = pd.read_csv(Pharmacogenetic_Associations_table_path_node_file, sep ='\t')
Pharmacogenetic_Associations_table_edge_df = pd.read_csv(Pharmacogenetic_Associations_table_path_edge_file, sep ='\t')

## Now starts to merge those individual parsed files
* current list of parsed files
* PharmGKB
* SIGNOR
* FDA Pharmacogenomics biomarker

In [49]:
## concatenate signor and cellmarker dfs
list_of_input_node_files = [FDA_Pharmacogenomic_biomarkers_node_df, PharmGKB_node_df, signor_node_df, PrimeKG_node_df, GtoPdB_node_df, CIViC_node_df, CPIC_node_df, Pharmacogenetic_Associations_table_node_df]

list_of_input_edge_files = [FDA_Pharmacogenomic_biomarkers_edge_df, PharmGKB_edge_df, signor_edge_df, PrimeKG_edge_df, GtoPdB_edge_df, CIViC_edge_df, CPIC_edge_df, Pharmacogenetic_Associations_table_edge_df]

PharmacogenomicsKG_node_df = pd.concat(list_of_input_node_files).drop_duplicates()
PharmacogenomicsKG_edge_df = pd.concat(list_of_input_edge_files).drop_duplicates()

In [50]:
print(len(PharmacogenomicsKG_node_df))
print(len(PharmacogenomicsKG_edge_df))

66399
1017010

In [53]:
## check if nan value in the object column
PharmacogenomicsKG_edge_filter_df = PharmacogenomicsKG_edge_df.dropna(subset=['object'])

print(len(PharmacogenomicsKG_edge_filter_df))

1017006

In [54]:
## check if nan value in the object column
PharmacogenomicsKG_edge_filter_df = PharmacogenomicsKG_edge_filter_df.dropna(subset=['subject'])

print(len(PharmacogenomicsKG_edge_filter_df))

1017006

In [55]:
PharmacogenomicsKG_edge_filter_df.head(3)

,subject,subject_name,subject_category,object,object_name,object_category,predicate,knowledge_source,knowledge_level,context_qualifier,agent_type,deploy_date,id,subject_direction_qualifier,object_direction_qualifier,object_aspect_qualifier,publications,provided_by,negated,attributes
0,RXCUI:2563966,Odevixibat,biolink:Drug,NCBIGene:8647,ABCB11,biolink:Gene,biolink:has_biomarker,FDA pharmacogenomics biomarkers table,knowledge_assertion,Gastroenterology,text_mining_agent,2025-09-04,4e1f7def-7e8d-5204-9826-56887ff5ecb5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RXCUI:2571074,Maralixibat,biolink:Drug,NCBIGene:8647,ABCB11,biolink:Gene,biolink:has_biomarker,FDA pharmacogenomics biomarkers table,knowledge_assertion,Gastroenterology,text_mining_agent,2025-09-04,d5f51f86-e8a1-5481-8105-cdd2d9efc023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RXCUI:2571074,Maralixibat,biolink:Drug,NCBIGene:5244,ABCB4,biolink:Gene,biolink:has_biomarker,FDA pharmacogenomics biomarkers table,knowledge_assertion,Gastroenterology,text_mining_agent,2025-09-04,ef3537de-0846-5bf9-b22a-5541c4214210,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Download all merged KG
* need to change to the name of concatenate dataframes

In [56]:
## Define the output path for node & edge files after formatting
download_path_node_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/Pharmacogenomics_KG_parsed_node_{version_number}.tsv'
download_path_edge_file = f'/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/Pharmacogenomics_KG_parsed_edge_{version_number}.tsv'

print(download_path_edge_file)

## download both node and edge files
## Download the result df
## disable download for testing
PharmacogenomicsKG_node_df.to_csv(download_path_node_file, sep ='\t', index=False)
PharmacogenomicsKG_edge_filter_df.to_csv(download_path_edge_file, sep ='\t', index=False)

/Users/Weiqi0/ISB_working/Ilya_lab/Translator/Pharmagenomics_KG/files/parsed/wQualityControl/Pharmacogenomics_KG_parsed_edge_08_10_2026.tsv